### ISSUE TITLE
A new HubBasics, a new To-Do list

### ISSUE THREAD

**Issue by LorgeN** [Fabricio20/HubBasics#45]
The new and rewritten plugin will have the same features as its predecessor, with more to come.

Features:
- [x] Disable/enable and customize join/leave messages
- [X] Double jump attribute
- [x] Keep/full food level in certain areas such as the spawn, or everywhere
- [x] Keep/full health level in certain areas such as the spawn, or everywhere
- [ ] Extensive BungeeCord support
- [X] Launch pads with proper settings
- [ ] Basic information signs
- [x] Fixed weather
- [x] Extensive MOTD settings (Alternating, color codes)
- [x] Automatic return to spawn when you fall into the void
- [x] Override and customize messages for any given command, such as /plugin with bypass permission
- [x] Predefined set of items your inventory must contain on connect
- [x] Automated broadcast system using the chat and boss bar
- [x] Per world configuration for settings where this is useful
- [ ] Magic clock system
- [ ] Warp system
- [ ] NameTagEdit system
- [x] Add support for changing all of the messages
- [x] Custom text holograms
- [ ] Stacker Hub Minigame
- [ ] Action bar broadcasts
