### ISSUE TITLE
Version 6.0?

### ISSUE THREAD

**Issue by LorgeN** [Fabricio20/HubBasics#65]
As some of you may have noticed, it has been a long time since anything happened here. This is due to school starting again, and various other personal reasons, resulting in both me and Fab not having enough time to work on the plugin. Even though it feels like I just pushed the latest commit yesterday, it has been months, resulting in the plugin being outdated, not working on the latest version, multiple bugs and so on. Instead of writing an essay, I'm just going to say this: Christmas holidays are coming, and so is the next version of HubBasics!

This new version can be found on the "development" branch, here on GitHub.
## **To-Do/Feature list:**
- [ ] Improved module system, using reflection (In combination with the Reflections library)
- [ ] Improved configuration system, with way more options and gadgets, including in-string variables, per-world configuration (As always)
- [ ] Less bugs (Hopefully)
- [ ] Support for multiple locales (Languages), including for items and similar
- [ ] MySQL data storage
- [ ] Basic BungeeCord support using plugin messages
- [ ] Plugin metrics
- [ ] Easy-to-use and efficient item serialization
- [ ] An API for other plugins, and proper documentation for **ALL** methods and classes
- [ ] Configuration/installation guide
- [ ] Improved version support and handling

## **Modules (As listed on the Spigot page)**

- [ ] Modify connect/disconnect messages
- [ ] Double-jump attribute
- [ ] Lock weather to current state
- [ ] Custom, alternating MOTDs
- [ ] Anti-void-fall
- [ ] No hunger/damage
- [ ] Launch pads
- [ ] Override commands
- [ ] "/hub" command
- [ ] Broadcasting system
- [ ] Fancy holograms
- [ ] Warps
- [ ] Items-on-connect system
- [ ] Create your own custom menus/GUIs

**Comment by Fabricio20** [comment]
Replaced by #81
