### ISSUE TITLE
6.0 Roadmap

### ISSUE THREAD

**Issue by Fabricio20** [Fabricio20/HubBasics#81]
This is the roadmap for the 6.0 release, compatible with 1.12.2.

- [ ] Disable or enable and customize your Join/Leave messages
- [X] Double jump attribute
- [X] Fixed Weather
- [ ] Extensive MOTD
- [X] Anti-VoidFall
- [X] Keep Food (Keeps food at 100%)
- [X] Keep Health (Keeps health at 100%)
- [ ] Launch Pads
- [ ] Override any command!
- [ ] /hub and /sethub ( /lobby as alias for /hub )
- [ ] Chat Announcer System
- [X] Boss Bar Announcer System
- [X] Custom Holograms
- [X] Warp System
- [X] JoinItem system
- [X] Custom Menus
- [ ] BungeeCord Support
- [ ] Basic Info Signs
- [ ] Stacker mini-game
- [ ] NameTagEdit System
- [X] Fully configurable with per-world options, and with permissions!
